import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, Bell, Check, ChevronDown, CircleHelp, Droplets, Leaf, LogOut, Plus, RefreshCw, Settings2, ShieldCheck, Sprout, Sun, Thermometer, Trash2, Wifi, WifiOff, Wind, X } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || '';
const profiles = { succulent:20, tomato:40, herb:35, indoor:30 };
async function api(path, { token, ...options } = {}) {
  const headers = { ...(options.body ? {'Content-Type':'application/json'} : {}), ...(token ? {Authorization:`Bearer ${token}`} : {}), ...(options.headers || {}) };
  const response = await fetch(`${API}${path}`, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || `Request failed (${response.status})`);
  return data;
}
function App() {
  const [token,setToken]=useState(localStorage.getItem('plantcare_token'));
  const [user,setUser]=useState(null), [devices,setDevices]=useState([]), [deviceId,setDeviceId]=useState('');
  const [history,setHistory]=useState([]), [alerts,setAlerts]=useState([]), [watering,setWatering]=useState([]);
  const [error,setError]=useState(''), [toast,setToast]=useState(''), [busy,setBusy]=useState(false), [showAdd,setShowAdd]=useState(false), [showGuide,setShowGuide]=useState(false), [showDelete,setShowDelete]=useState(false);
  const [authMode,setAuthMode]=useState('login'), [authEmail,setAuthEmail]=useState(''), [authPassword,setAuthPassword]=useState('');
  const device=devices.find(d=>d.id===deviceId) || devices[0];
  const notify=(message)=>{setToast(message);setTimeout(()=>setToast(''),3200)};
  const logout=()=>{localStorage.removeItem('plantcare_token');setToken(null);setUser(null);setDevices([]);setDeviceId('')};
  async function refresh(t=token, selected=deviceId) {
    if(!t)return;
    try {
      const [me, initialList, alertRows]=await Promise.all([api('/api/auth/me',{token:t}),api('/api/devices',{token:t}),api('/api/alerts',{token:t})]);
      const initialChoice=initialList.find(d=>d.id===selected)||initialList[0];
      if(initialChoice?.virtual_sensor_running){await api(`/api/devices/${initialChoice.id}/virtual-sensor/tick`,{token:t,method:'POST'});}
      const list=initialChoice?.virtual_sensor_running?await api('/api/devices',{token:t}):initialList;
      setUser(me);setDevices(list);setAlerts(alertRows);
      const chosen=list.find(d=>d.id===selected)||list[0];
      if(chosen){setDeviceId(chosen.id);const [hist,waters]=await Promise.all([api(`/api/devices/${chosen.id}/history?limit=100`,{token:t}),api(`/api/devices/${chosen.id}/watering-history`,{token:t})]);setHistory(hist);setWatering(waters)} else {setHistory([]);setWatering([])}
      setError('');
    } catch(e){if(e.message.includes('token')||e.message.includes('Bearer'))logout();else setError(e.message)}
  }
  useEffect(()=>{if(token)refresh(token);},[token]);
  useEffect(()=>{if(!token)return;const timer=setInterval(()=>refresh(token,deviceId),10000);return()=>clearInterval(timer)},[token,deviceId]);
  async function submitAuth(e){e.preventDefault();setBusy(true);setError('');try{const data=await api(`/api/auth/${authMode}`,{method:'POST',body:JSON.stringify({email:authEmail,password:authPassword})});localStorage.setItem('plantcare_token',data.access_token);setToken(data.access_token)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function updateThreshold(value){try{await api(`/api/devices/${device.id}/threshold`,{token,method:'PUT',body:JSON.stringify({threshold:Number(value)})});notify('Moisture target saved');refresh(token,device.id)}catch(e){setError(e.message)}}
  async function toggleAuto(){try{await api(`/api/devices/${device.id}/auto-water`,{token,method:'PUT',body:JSON.stringify({enabled:!device.auto_water})});notify(`Automatic watering ${device.auto_water?'paused':'enabled'}`);refresh(token,device.id)}catch(e){setError(e.message)}}
  async function toggleVirtualSensor(){setBusy(true);try{const enabled=!device.virtual_sensor_running;await api(`/api/devices/${device.id}/virtual-sensor`,{token,method:'PUT',body:JSON.stringify({enabled})});notify(enabled?'Virtual sensor started · readings are on the way':'Virtual sensor paused');await refresh(token,device.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function waterNow(){setBusy(true);try{await api(`/api/devices/${device.id}/water`,{token,method:'POST',body:JSON.stringify({duration_seconds:3})});notify('Water pulse queued · 3 seconds');refresh(token,device.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function deletePlant(){if(!device)return;const gone=device.plant_name;setBusy(true);try{await api(`/api/devices/${device.id}`,{token,method:'DELETE'});setShowDelete(false);setDeviceId('');notify(`${gone} removed`);await refresh(token,'')}catch(e){setShowDelete(false);setError(e.message)}finally{setBusy(false)}}
  async function acknowledge(id){try{await api(`/api/alerts/${id}/acknowledge`,{token,method:'PUT'});refresh(token,device.id)}catch(e){setError(e.message)}}
  async function createDevice(e){e.preventDefault();const fd=new FormData(e.currentTarget),type=fd.get('plant_type'),virtualSensor=fd.get('virtual_sensor')==='on';setBusy(true);try{const result=await api('/api/devices',{token,method:'POST',body:JSON.stringify({id:fd.get('id'),plant_name:fd.get('plant_name'),plant_type:type,location:fd.get('location'),threshold:Number(fd.get('threshold')||profiles[type]),auto_water:true,virtual_sensor:virtualSensor})});await navigator.clipboard?.writeText(result.device_key).catch(()=>{});setShowAdd(false);notify(virtualSensor?'Plant added · virtual readings starting; key copied for hardware':'Plant added · device key copied');await refresh(token,result.device.id)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const latest=device?.latest;
  const healthy=latest && latest.soil_moisture>=device.threshold;
  const chartData=useMemo(()=>history.map(r=>({ ...r, time:new Date(r.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}) })),[history]);
  if(!token)return <main className="auth-page"><div className="auth-left"><div className="brand"><span className="brand-mark"><Sprout size={19}/></span><span>plantcare<span className="brand-dot">.</span></span></div><div className="auth-story"><span className="eyebrow">A little more care, every day</span><h1>Grow with<br/><em>good data.</em></h1><p>Keep an eye on your plants, understand their rhythms, and water with confidence from anywhere.</p><div className="auth-badges"><span><ShieldCheck size={15}/>Private by design</span><span><Activity size={15}/>Live plant signals</span></div></div><div className="auth-bottom">CLOUD-CONNECTED PLANT CARE <span>·</span> BUILT FOR GROWTH</div></div><div className="auth-right"><form className="auth-form" onSubmit={submitAuth}><span className="eyebrow">{authMode==='login'?'WELCOME BACK':'GET STARTED'}</span><h2>{authMode==='login'?'Sign in to your garden':'Create your account'}</h2><p className="muted">{authMode==='login'?'Your little corner of the garden is waiting.':'Start monitoring your plants in a few simple steps.'}</p>{error&&<div className="error-box">{error}</div>}<label>Email address<input type="email" autoComplete="email" required maxLength="254" value={authEmail} onChange={e=>setAuthEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={authMode==='login'?'current-password':'new-password'} minLength={authMode==='login'?1:12} maxLength="128" required value={authPassword} onChange={e=>setAuthPassword(e.target.value)}/>{authMode==='register'&&<small>Use at least 12 characters.</small>}</label><button className="button primary wide" disabled={busy}>{busy?'Please wait…':authMode==='login'?'Sign in':'Create account'}</button><p className="switch-auth">{authMode==='login'?"New to PlantCare?":"Already have an account?"} <button type="button" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setError('')}}>{authMode==='login'?'Create an account':'Sign in'}</button></p></form></div></main>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sprout size={19}/></span><span>plantcare<span className="brand-dot">.</span></span></div><div className="side-label">YOUR SPACE</div><button className="nav-item active"><Leaf size={17}/> My garden <span className="nav-count">{devices.length}</span></button><button className="nav-item" onClick={()=>document.getElementById('alerts')?.scrollIntoView({behavior:'smooth'})}><Bell size={17}/> Alerts {alerts.filter(a=>!a.acknowledged).length>0&&<span className="alert-count">{alerts.filter(a=>!a.acknowledged).length}</span>}</button><div className="side-label plants-label">PLANTS <button aria-label="Add plant" onClick={()=>setShowAdd(true)}><Plus size={15}/></button></div>{devices.map(d=><button className={`plant-link ${device?.id===d.id?'selected':''}`} onClick={()=>{setDeviceId(d.id);refresh(token,d.id)}} key={d.id}><span className="plant-avatar"><Sprout size={15}/></span><span>{d.plant_name}<small>{d.status==='online'?'Connected':'No recent signal'}</small></span><i className={d.status==='online'?'online-dot':'offline-dot'}/></button>)}{!devices.length&&<p className="empty-small">Your garden is ready for its first plant.</p>}<div className="sidebar-spacer"/><div className="side-help" onClick={()=>setShowGuide(true)}><CircleHelp size={17}/><span>Quick start guide</span></div><div className="profile"><span className="profile-avatar">{user?.email?.slice(0,1).toUpperCase()}</span><span className="profile-copy">{user?.email}<small>Garden owner</small></span><button aria-label="Sign out" onClick={logout}><LogOut size={16}/></button></div></aside>
  <main className="main"><header className="topbar"><div className="breadcrumbs">My garden <span>/</span> <strong>{device?.plant_name||'Overview'}</strong></div><div className="top-actions"><span className="live-label"><i/> AUTO-REFRESH 10S</span><button className="icon-button" title="Refresh" onClick={()=>refresh()}><RefreshCw size={16}/></button><button className="button add-button" onClick={()=>setShowAdd(true)}><Plus size={16}/> Add a plant</button></div></header><div className="content">
  {!device?<section className="welcome-card"><div className="welcome-art"><span>✳</span><span>⌁</span><span>✿</span></div><span className="eyebrow">YOUR GARDEN STARTS HERE</span><h1>Make room<br/>for something <em>green.</em></h1><p>Add a plant and start its virtual sensor. Readings and moisture trends appear automatically—no hardware or Terminal required.</p><button className="button primary" onClick={()=>setShowAdd(true)}><Plus size={16}/> Add your first plant</button><div className="welcome-note"><span>01</span> Add a plant <b>→</b><span>02</span> Start virtual readings <b>→</b><span>03</span> Watch it grow</div></section>:<>
  <section className="page-heading"><div><div className="eyebrow">YOUR GARDEN · {new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}</div><h1>{device.plant_name}<button className="select-chevron" onClick={()=>document.getElementById('plant-select').classList.toggle('open')}><ChevronDown size={17}/></button><div className="plant-dropdown" id="plant-select">{devices.map(d=><button key={d.id} onClick={()=>{setDeviceId(d.id);refresh(token,d.id);document.getElementById('plant-select').classList.remove('open')}}>{d.plant_name}</button>)}</div></h1><div className="plant-subtitle"><span className="species-chip">{device.plant_type}</span>{device.location&&<span>{device.location}</span>}<span className={`device-state ${device.status==='online'?'is-online':'is-offline'}`}>{device.status==='online'?<Wifi size={13}/>:<WifiOff size={13}/>} {device.status==='online'?'Device online':'Device offline'}</span></div></div><div className="heading-right"><span className={`health-pill ${healthy?'healthy':'dry'}`}><i/>{!latest?'Awaiting reading':healthy?'Looking healthy':'Thirsty · needs water'}</span><span className="last-seen">Last signal {latest?new Date(latest.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'—'}</span><button className="remove-plant" onClick={()=>setShowDelete(true)}><Trash2 size={13}/> Remove plant</button></div></section>
  {error&&<div className="error-banner">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}
  <section className={`virtual-sensor-banner ${device.virtual_sensor_running?'running':''}`}><span className="virtual-sensor-mark"><Activity size={17}/></span><div className="virtual-sensor-copy"><strong>{device.virtual_sensor_running?'Virtual sensor is running':'Want to see readings now?'}</strong><small>{device.virtual_sensor_running?'Simulated readings update while this garden is open.':'Start a no-hardware demo. No Terminal or device key needed.'}</small></div><button className="button" disabled={busy} onClick={toggleVirtualSensor}>{busy?'Please wait…':device.virtual_sensor_running?'Pause virtual sensor':'Start virtual sensor'}</button></section>
  <section className="metric-grid"><Metric title="SOIL MOISTURE" value={latest?latest.soil_moisture.toFixed(0):'—'} unit="%" icon={<Droplets/>} tone="green" sub={latest?`Target · ${device.threshold}%`:'Waiting for sensor'}/><Metric title="TEMPERATURE" value={latest?latest.temperature.toFixed(1):'—'} unit="°C" icon={<Thermometer/>} tone="sand" sub="Ambient air"/><Metric title="HUMIDITY" value={latest?latest.humidity.toFixed(0):'—'} unit="%" icon={<Wind/>} tone="blue" sub="Relative humidity"/><Metric title="LIGHT" value={latest?latest.light_level.toFixed(0):'—'} unit="%" icon={<Sun/>} tone="yellow" sub="Daily exposure"/></section>
  <section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-head"><div><span className="eyebrow">THE LAST 24 HOURS</span><h2>Moisture over time</h2></div><span className="chart-legend"><i/> Soil moisture</span></div>{chartData.length>1?<ResponsiveContainer width="100%" height={235}><AreaChart data={chartData} margin={{top:10,right:8,left:-22,bottom:0}}><defs><linearGradient id="moistureFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4f7e5f" stopOpacity={.22}/><stop offset="95%" stopColor="#4f7e5f" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e9ece5"/><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fill:'#92988f',fontSize:11}} minTickGap={28}/><YAxis domain={[0,100]} axisLine={false} tickLine={false} tick={{fill:'#92988f',fontSize:11}} tickFormatter={v=>`${v}%`}/><Tooltip contentStyle={{borderRadius:12,border:'1px solid #e8ece5',boxShadow:'0 8px 30px #1e3b2515'}} formatter={v=>[`${v}%`,'Moisture']}/><Area type="monotone" dataKey="soil_moisture" stroke="#4f7e5f" strokeWidth={2.5} fill="url(#moistureFill)" activeDot={{r:5,strokeWidth:0}}/></AreaChart></ResponsiveContainer>:<div className="chart-empty"><span><Activity size={19}/></span><p>{latest?'Collecting readings · trend appears after the next update':'Connect the simulator to start your moisture history'}</p></div>}<div className="chart-foot"><span><i className="threshold-dash"/> Target threshold · {device.threshold}%</span><span>{history.length} readings shown</span></div></article>
  <article className="panel control-panel"><div className="panel-head"><div><span className="eyebrow">CARE SETTINGS</span><h2>Watering</h2></div><span className="control-icon"><Droplets size={17}/></span></div><div className="auto-row"><div><strong>Automatic watering</strong><small>{device.auto_water?'Waters when soil falls below target':'Manual control only'}</small></div><button role="switch" aria-checked={device.auto_water} className={`toggle ${device.auto_water?'on':''}`} onClick={toggleAuto}><i/></button></div><div className="threshold-block"><div className="threshold-label"><span>Moisture target</span><strong>{device.threshold}%</strong></div><input type="range" min="5" max="90" value={device.threshold} onChange={e=>setDevices(ds=>ds.map(d=>d.id===device.id?{...d,threshold:Number(e.target.value)}:d))} onMouseUp={e=>updateThreshold(e.target.value)} onTouchEnd={e=>updateThreshold(e.currentTarget.value)} style={{'--range':`${(device.threshold-5)/85*100}%`}}/><div className="range-ends"><span>5% · drier</span><span>90% · wetter</span></div></div><div className="pump-status"><span className="pump-icon"><Droplets size={17}/></span><span><strong>Virtual pump</strong><small>Safe pulse · max 10 sec</small></span><span className="pump-off"><i/> STANDBY</span></div><button className="button water-button" disabled={busy||!latest} onClick={waterNow}><Droplets size={16}/>{busy?'Sending…':'Water now · 3 sec'}</button><p className="cooldown-note"><ShieldCheck size={13}/> 5-minute cooldown helps prevent overwatering</p></article></section>
  <section className="lower-grid"><article className="panel events-panel"><div className="panel-head"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Watering history</h2></div><span className="subtle-count">{watering.length} events</span></div>{watering.length?<div className="event-list">{watering.slice(0,5).map(w=><div className="event-row" key={w.id}><span className="event-icon"><Droplets size={15}/></span><div><strong>{w.trigger_type==='manual'?'Manual watering':'Automatic watering'}</strong><small>{new Date(w.created_at).toLocaleString()}</small></div><span className={`event-state ${w.status}`}>{w.status}</span></div>)}</div>:<div className="empty-rows">No watering events yet. Your plant is doing just fine.</div>}</article><article className="panel alerts-panel" id="alerts"><div className="panel-head"><div><span className="eyebrow">KEEP AN EYE OUT</span><h2>Alerts</h2></div><Bell size={17} className="muted-icon"/></div>{alerts.length?<div className="alert-list">{alerts.slice(0,4).map(a=><div className={`alert-row ${a.acknowledged?'acknowledged':''}`} key={a.id}><span className={`alert-mark ${a.level}`}/><div><strong>{a.message}</strong><small>{new Date(a.created_at).toLocaleString()}</small></div>{!a.acknowledged&&<button title="Acknowledge" onClick={()=>acknowledge(a.id)}><Check size={15}/></button>}</div>)}</div>:<div className="all-well"><span>✿</span><div><strong>All is well</strong><small>No alerts at the moment</small></div></div>}</article></section>
  </>}
  <footer className="footer"><span>PLANTCARE · CLOUD-CONNECTED GARDEN</span><span>SIMULATED SENSORS <i/> ENCRYPTED API</span></footer></div></main>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}
  {showAdd&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShowAdd(false)}><form className="modal" onSubmit={createDevice}><button type="button" className="modal-close" onClick={()=>setShowAdd(false)}><X size={18}/></button><span className="eyebrow">GROW YOUR GARDEN</span><h2>Add a plant</h2><p className="muted">Your virtual sensor starts automatically. No hardware or Terminal needed.</p><label>Plant name<input name="plant_name" required maxLength="80" placeholder="e.g. Balcony basil"/></label><div className="form-split"><label>Plant profile<select name="plant_type" onChange={e=>document.getElementById('new-threshold').value=profiles[e.target.value]}><option value="indoor">Indoor plant · 30%</option><option value="tomato">Tomato · 40%</option><option value="herb">Herb · 35%</option><option value="succulent">Succulent · 20%</option></select></label><label>Device ID<input name="id" required pattern="[A-Za-z0-9][A-Za-z0-9_-]{1,47}" placeholder="PLANT-001" maxLength="48"/></label></div><div className="form-split"><label>Location<input name="location" maxLength="100" placeholder="Kitchen window"/></label><label>Moisture target (%)<input id="new-threshold" name="threshold" type="number" min="5" max="90" defaultValue="30" required/></label></div><label className="virtual-sensor-choice"><input type="checkbox" name="virtual_sensor" defaultChecked/><span><strong>Start virtual sensor</strong><small>Generate realistic readings and chart changes automatically.</small></span></label><div className="modal-note"><ShieldCheck size={16}/> Device key is copied for optional hardware. The virtual sensor does not need it.</div><button className="button primary wide" disabled={busy}>{busy?'Creating…':'Create plant'}</button></form></div>}
  {showDelete&&device&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!busy&&setShowDelete(false)}><div className="modal delete-modal" role="alertdialog" aria-labelledby="delete-title"><button type="button" className="modal-close" onClick={()=>setShowDelete(false)}><X size={18}/></button><span className="eyebrow">REMOVE FROM GARDEN</span><h2 id="delete-title">Remove {device.plant_name}?</h2><p className="muted">This permanently deletes the plant and its device <code>{device.id}</code>, along with all readings, watering history and alerts. The device key stops working, so a running simulator will get authentication errors. This can’t be undone.</p><div className="delete-actions"><button className="button" disabled={busy} onClick={()=>setShowDelete(false)}>Keep plant</button><button className="button danger" disabled={busy} onClick={deletePlant}>{busy?'Removing…':'Yes, remove it'}</button></div></div></div>}
  {showGuide&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShowGuide(false)}><div className="modal guide-modal"><button className="modal-close" onClick={()=>setShowGuide(false)}><X size={18}/></button><span className="eyebrow">QUICK START</span><h2>Bring your plant online</h2><ol><li><b>For a quick demo</b><span>Choose <b>Start virtual sensor</b> on the plant dashboard. Readings update automatically while the page is open.</span></li><li><b>For hardware</b><span>Use the one-time device key with an ESP32 or the Python simulator. The key is not needed for virtual readings.</span></li></ol><button className="button primary wide" onClick={()=>setShowGuide(false)}>Got it</button></div></div>}
  </div>;
}
function Metric({title,value,unit,icon,tone,sub}){return <article className="metric-card"><div className="metric-top"><span className="eyebrow">{title}</span><span className={`metric-icon ${tone}`}>{icon}</span></div><div className="metric-value">{value}<small>{unit}</small></div><span className="metric-sub">{sub}</span></article>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
